// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using arbeidskrav_del_1.Data;

#nullable disable

namespace arbeidskrav_del_1.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    partial class BooksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("arbeidskrav_del_1.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            ISBN = "978-1-11111-111-1",
                            InStock = 10,
                            PublicationYear = 2020,
                            Title = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane Smith",
                            ISBN = "978-1-22222-222-2",
                            InStock = 5,
                            PublicationYear = 2021,
                            Title = "Advanced C#"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mark Johnson",
                            ISBN = "978-1-33333-333-3",
                            InStock = 7,
                            PublicationYear = 2019,
                            Title = "EF Core in Depth"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Alice Brown",
                            ISBN = "978-1-44444-444-4",
                            InStock = 12,
                            PublicationYear = 2022,
                            Title = "ASP.NET Core Guide"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Bob Martin",
                            ISBN = "978-1-55555-555-5",
                            InStock = 8,
                            PublicationYear = 2018,
                            Title = "LINQ Essentials"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Carla White",
                            ISBN = "978-1-66666-666-6",
                            InStock = 9,
                            PublicationYear = 2020,
                            Title = "Blazor Unleashed"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Daniel Lee",
                            ISBN = "978-1-77777-777-7",
                            InStock = 4,
                            PublicationYear = 2017,
                            Title = "Design Patterns C#"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eve Adams",
                            ISBN = "978-1-88888-888-8",
                            InStock = 6,
                            PublicationYear = 2019,
                            Title = "Clean Code C#"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Frank Green",
                            ISBN = "978-1-99999-999-9",
                            InStock = 11,
                            PublicationYear = 2021,
                            Title = "Microservices with .NET"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Grace Hall",
                            ISBN = "978-1-10101-101-0",
                            InStock = 10,
                            PublicationYear = 2020,
                            Title = "Unit Testing in C#"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Hank King",
                            ISBN = "978-1-11102-101-1",
                            InStock = 7,
                            PublicationYear = 2018,
                            Title = "Async Programming C#"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Irene Scott",
                            ISBN = "978-1-12121-121-2",
                            InStock = 3,
                            PublicationYear = 2017,
                            Title = "WPF Fundamentals"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Jack Taylor",
                            ISBN = "978-1-13131-131-3",
                            InStock = 5,
                            PublicationYear = 2022,
                            Title = "MAUI Essentials"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Karen Young",
                            ISBN = "978-1-14141-141-4",
                            InStock = 8,
                            PublicationYear = 2020,
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Leo Wright",
                            ISBN = "978-1-15151-151-5",
                            InStock = 6,
                            PublicationYear = 2019,
                            Title = "SignalR in Action"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Mia Roberts",
                            ISBN = "978-1-16161-161-6",
                            InStock = 9,
                            PublicationYear = 2021,
                            Title = "Azure for .NET Developers"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Nathan Evans",
                            ISBN = "978-1-17171-171-7",
                            InStock = 7,
                            PublicationYear = 2021,
                            Title = "Docker for .NET"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Olivia Perez",
                            ISBN = "978-1-18181-181-8",
                            InStock = 5,
                            PublicationYear = 2022,
                            Title = "Kubernetes .NET Apps"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Peter Hall",
                            ISBN = "978-1-19191-191-9",
                            InStock = 6,
                            PublicationYear = 2020,
                            Title = "gRPC with .NET"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Quinn Lewis",
                            ISBN = "978-1-20202-202-0",
                            InStock = 12,
                            PublicationYear = 2022,
                            Title = "Modern C# Patterns"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
